# Generated by Django 3.0.5 on 2020-05-09 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('objectives', models.TextField()),
                ('outcome_perc', models.IntegerField()),
                ('estimated_budget', models.IntegerField()),
                ('actual_budget', models.IntegerField()),
                ('started_date', models.DateField(null=True)),
                ('finished_date', models.DateField(null=True)),
                ('top_proj', models.BooleanField(default=False)),
                ('mande_report', models.FileField(null=True, upload_to='Reports/')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_txt', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
