# Generated by Django 3.0.5 on 2020-05-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=models.EmailField(default=None, max_length=254), max_length=100),
        ),
    ]
